# Generated by Django 3.2.9 on 2021-11-26 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='title',
            field=models.CharField(default='Title Missing', max_length=100),
            preserve_default=False,
        ),
    ]
