# Generated by Django 3.2.9 on 2021-11-27 22:16
import os

from django.db import migrations


def generate_superuser(apps, schema_editor):
    from django.contrib.auth import get_user_model
    User = get_user_model()

    DJANGO_SU_NAME = None
    DJANGO_SU_EMAIL = None
    DJANGO_SU_PASSWORD = None

    User.objects.create_superuser(
        username=DJANGO_SU_NAME,
        email=DJANGO_SU_EMAIL,
        password=DJANGO_SU_PASSWORD,
    )


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(generate_superuser)
    ]
